import { ICardThreat } from './card.treat';

export const ThreatCards: Array<ICardThreat> = 
    [
        { 
            id: 301, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 201,
        },
        { 
            id: 302, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 202,
        },        
        { 
            id: 303, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 203,
        },        
        { 
            id: 304, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 204,
        },        
        { 
            id: 305, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 205,
        },        
        { 
            id: 306, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 206,
        },        
        { 
            id: 307, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 207,
        },        
        { 
            id: 308, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 208,
        },        
        { 
            id: 309, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 209,
        },        
        { 
            id: 310, 
            name: 'with the raft to the wreck', 
            freeCards: 1, 
            levelValues: [0, 1, 3], 
            revardCardID: 210,
        },                                                                
        { 
            id: 311, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 211,
        },    
        { 
            id: 312, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 212,
        },    
        { 
            id: 313, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 213,
        },    
        { 
            id: 314, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 214,
        },    
        { 
            id: 315, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 215,
        },    
        { 
            id: 316, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 216,
        },    
        { 
            id: 317, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 217,
        },    
        { 
            id: 318, 
            name: 'exploring the island', 
            freeCards: 2, 
            levelValues: [1, 3, 6], 
            revardCardID: 218,
        },    
        { 
            id: 319, 
            name: 'further exploring the island', 
            freeCards: 3, 
            levelValues: [2, 5, 8], 
            revardCardID: 219,
        },      
        { 
            id: 320, 
            name: 'further exploring the island', 
            freeCards: 3, 
            levelValues: [2, 5, 8], 
            revardCardID: 220,
        },      
        { 
            id: 321, 
            name: 'further exploring the island', 
            freeCards: 3, 
            levelValues: [2, 5, 8], 
            revardCardID: 221,
        },      
        { 
            id: 322, 
            name: 'further exploring the island', 
            freeCards: 3, 
            levelValues: [2, 5, 8], 
            revardCardID: 222,
        },      
        { 
            id: 323, 
            name: 'further exploring the island', 
            freeCards: 3, 
            levelValues: [2, 5, 8], 
            revardCardID: 223,
        },                                                            
        { 
            id: 324, 
            name: 'further exploring the island', 
            freeCards: 3, 
            levelValues: [2, 5, 8], 
            revardCardID: 224,
        },
        { 
            id: 325, 
            name: 'wild animals', 
            freeCards: 4, 
            levelValues: [4, 7, 11], 
            revardCardID: 225,
        },      
        { 
            id: 326, 
            name: 'wild animals', 
            freeCards: 4, 
            levelValues: [4, 7, 11], 
            revardCardID: 226,
        },      
        { 
            id: 327, 
            name: 'wild animals', 
            freeCards: 4, 
            levelValues: [4, 7, 11], 
            revardCardID: 227,
        },                                                            
        { 
            id: 328, 
            name: 'wild animals', 
            freeCards: 4, 
            levelValues: [4, 7, 11], 
            revardCardID: 228,
        },                
        { 
            id: 329, 
            name: 'cannibals', 
            freeCards: 5, 
            levelValues: [5, 9, 14], 
            revardCardID: 227,
        },                                                            
        { 
            id: 330, 
            name: 'cannibals', 
            freeCards: 5, 
            levelValues: [5, 9, 14], 
            revardCardID: 228,
        },  
    ];